"""Pydantic models for the data-entry API request/response contracts.

Kept in one file so the shape of every payload is easy to audit.  All models
are strict about optional fields to avoid silent data loss when Oxigraph
returns sparse results for entities that are missing recommended properties.
"""

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field


class TripleObject(BaseModel):
    predicate: str
    object: str
    objectType: str
    datatype: str | None = None
    language: str | None = None


class EntityData(BaseModel):
    """Input model for `POST /api/data` and `POST /api/validate`.

    Attributes:
        shapeId: Full URI of the SHACL NodeShape that constrains this entity
            (e.g. `"https://rfdb.it/data/PlaceShape"`).
        data: Raw JSON-LD object.  Must carry a `@context` and `@type`; `@id`
            may be absent (it will be auto-generated by `assign_entity_id`).
        originalTriples: List of TripleObject for predicates the user edited (update only).
    """

    shapeId: str
    data: dict[str, Any]
    originalTriples: list[TripleObject] | None = None


class DataListItem(BaseModel):
    """A single row in the record list panel.

    `label` and `labelLang` come from a SPARQL SAMPLE over all `rdfs:label`
    values so the row always shows exactly one label even when the entity has
    multiple language variants.
    """

    id: str
    label: Optional[str] = None
    labelLang: Optional[str] = None
    status: str = "unknown"
    updatedAt: Optional[str] = None


class DataListResponse(BaseModel):
    """Paginated response for `GET /api/data/list`.

    `total` is the full result count (not capped by `limit`) so the frontend
    can render accurate pagination controls.
    """

    shapeId: str
    total: int
    items: list[DataListItem]


class ValidationResult(BaseModel):
    """Mirrors a SHACL `sh:ValidationReport`.  Returned by both the dry-run
    validate endpoint and embedded inside `DataCreateResponse` on every write.
    """

    conforms: bool = True
    violations: list[dict[str, Any]] = Field(default_factory=list)


class DataCreateResponse(BaseModel):
    """Response for `POST /api/data`.

    When `success` is False the entity was **not** stored; the frontend shows
    the `validationReport` violations and lets the user correct the form.
    """

    success: bool
    entityId: Optional[str] = None
    validationReport: ValidationResult
